apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blur-image-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: test.hemery.ovh # nom de domaine pour lequel le trafic est dirigé
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blur-image-service
            port:
              name: http
